
apiVersion: v1
kind: Pod
metadata:
  name: projectedvol-pod
spec:
  containers:
  - name: pv-container
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
    - name: test-volume
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: test-volume
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pswd


