
apiVersion: v1
kind: Pod
metadata:
  name: redis-vol
spec:
  containers:
  - name: redisvol-container
    image: redis
    volumeMounts:
    - name: redis-volume
      mountPath: /data
  volumes:
  - name: redis-volume
    emptyDir: {}



