
apiVersion: v1
kind: Service
metadata:
  name: serve-nginx
  labels:
    run: my-nginx
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: my-nginx




