==============================================================================
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db-container
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123@abc"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: wp-container
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

===============================================================================

#################### resource-pod.yaml (version 2) #############################

===============================================================================

apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db-container
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123@abc"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "512m"
  - name: wp-container
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "512m"

=============================================================================


